version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: password
      MYSQL_DB: dvwadb
      MYSQL_HOST: db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dvwadb
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:



